export const skills = [
  "Accounting",
  "Advertising",
  "Agile Development",
  "Analytics",
  "Android Development",
  "Artificial Intelligence",
  "Auditing",
  "AutoCAD",
  "B2B Marketing",
  "B2C Marketing",
  "Big Data",
  "Blogging",
  "Brand Management",
  "Budgeting",
  "Business Analysis",
  "Business Development",
  "Business Intelligence",
  "Business Planning",
  "C#",
  "C++",
  "Change Management",
  "Cloud Computing",
  "Coaching",
  "Communication",
  "Compliance",
  "Content Management",
  "Content Marketing",
  "Copywriting",
  "Corporate Finance",
  "Corporate Law",
  "Corporate Strategy",
  "Creative Writing",
  "CRM",
  "CSS",
  "Customer Service",
  "Data Analysis",
  "Data Entry",
  "Data Mining",
  "Data Science",
  "Database Administration",
  "Design",
  "Digital Marketing",
  "Direct Marketing",
  "E-commerce",
  "Editing",
  "Email Marketing",
  "Employee Relations",
  "Engineering",
  "Enterprise Architecture",
  "Entrepreneurship",
  "Event Planning",
  "Excel",
  "Facebook Marketing",
  "Financial Analysis",
  "Financial Modeling",
  "Financial Planning",
  "Financial Reporting",
  "Forecasting",
  "Foreign Languages",
  "Front-end Development",
  "Fundraising",
  "Game Development",
  "Google AdWords",
  "Graphic Design",
  "Healthcare Management",
  "Human Resources",
  "HTML",
  "Illustration",
  "Inbound Marketing",
  "Information Security",
  "Information Technology",
  "Insurance",
  "Interior Design",
  "International Business",
  "Internet Research",
  "Inventory Management",
  "Investment Banking",
  "iOS Development",
  "IT Management",
  "Java",
  "JavaScript",
  "jQuery",
  "Leadership",
  "Legal Writing",
  "Logistics",
  "Machine Learning",
  "Management",
  "Market Research",
  "Marketing",
  "Marketing Automation",
  "Mathematics",
  "Media Relations",
  "Microsoft Office",
  "Mobile App Development",
  "Mobile Marketing",
  "MySQL",
  "Negotiation",
  "Network Administration",
  "Non-profit Management",
  "Objective-C",
  "Operations Management",
  "Organizational Development",
  "Payroll",
  "Perl",
  "Photoshop",
  "PHP",
  "PMP",
  "Policy Analysis",
  "PowerPoint",
  "PR",
  "Presentation Skills",
  "Press Releases",
  "Procurement",
  "Product Management",
  "Product Marketing",
  "Project Management",
  "Proofreading",
  "Proposal Writing",
  "Public Speaking",
  "Python",
  "Quality Assurance",
  "QuickBooks",
  "Recruiting",
  "Research",
  "Risk Management",
  "Ruby",
  "Sales",
  "Salesforce",
  "SAP",
  "Search Engine Marketing",
  "Search Engine Optimization",
  "Security",
  "SEM",
  "SEO",
  "Social Media Marketing",
  "Software Development",
  "Software Engineering",
  "Spanish",
  "SQL",
  "Statistics",
  "Strategic Planning",
  "Supply Chain Management",
  "Swift",
  "System Administration",
  "Tableau",
  "Taxation",
  "Team Building",
  "Technical Writing",
  "Telecommunications",
  "Time Management",
  "Training",
  "Translation",
  "Travel Planning",
  "Troubleshooting",
  "Twitter Marketing",
  "Typing",
  "UI Design",
  "Unix",
  "User Experience Design",
  "User Interface Design",
  "Vendor Management",
  "Video Editing",
  "Video Production",
  "Virtual Assistant",
  "Visual Basic",
  "Visual Design",
  "Web Analytics",
  "Web Design",
  "Web Development",
  "Windows Server",
  "WordPress",
  "Writing",
  "XML",
];
